### ISSUE TITLE
Unable to update some settings in on-premises due to Authentication error

### ISSUE THREAD

**Issue by sivakesava6666** [seanmcne/OrgDbOrgSettings#73]
Settings failing with update:
"UseFilteringMethodOfSyncingMailboxOnlyForCorrelation".
"IgnoreConversationIndexAndInReplyToForCorrelation".
"ResolveForInactiveEntities".

Error details:
![image](https://user-images.githubusercontent.com/56884770/119013947-1ce63480-b9b5-11eb-91f1-7efdb3bd5aa9.png)

On-Premises CRM version:
9.0.22.8

**Comment by seanmcne** [comment]
The version of your onprem deployment appears to be missing the setting you want to add: 
![image](https://user-images.githubusercontent.com/2292260/120518299-0e295580-c397-11eb-8290-be0cb2b1d47d.png)

You may require an update which contains these settings.

**Comment by siovchev0** [comment]
Hi Sean,
Thanks for the answer.
Actually, the settings are available on said version. The problem comes only after enabling IFD. The solution expects only kerberos authentication. The same settings could be updated fine if IFD is not set up. Even before enabling claims-based auth.
-
Fiddler logs show kerberosmixed is called. Disabling the kerberos endpoint did not help.
The solution itself may call the wrong crmservice.
=
Could you provide your feedback on the above?
Thank you in advance.

**Comment by seanmcne** [comment]
Thanks for the update!  Do you have an example you can share of what this looks like in the UI?  It should be accessing the API using the auth context of the user who loaded the page - the exception should be what it is seeing from the HTTP response from the server.
